#!/bin/bash
# Lists as many items as can fit on the terminal, and only one per line.

if [ -n "$1" ]; then
	if [ "$1" == "usage" ]; then
		echo "    fit [TERM]"
		echo "      Lists as many items as can fit on the terminal, and only one per line."
		echo ""
		exit
	fi
	shift
fi

TERMINAL_FIT_SUB="sed -e '$(expr $(tput lines) - 3),\$d' -e 's/\(^\x1B\[[0-9;]*[mK]\)\?\([^\x1B]\{$(expr $(tput cols - 1) - 1)\}\).*$/\1\2…/g'"

export TODOTXT_FINAL_FILTER=$TODOTXT_FINAL_FILTER" | "$TERMINAL_FIT_SUB

_list "$TODO_FILE" "$@"

